<?php

declare(strict_types=1);

namespace Tbessenreither\MultiLevelCache\Tests\Interface\Commands\TestFiles;



/**
 * Autogenerated by MLC CachedServiceGenerator
 * Do not edit this Interface manually
 */
interface TargetClassInterface{


    public function exampleMethod(): void;


}
