<?php

declare(strict_types=1);

namespace Tbessenreither\MultiLevelCache\CachedServiceGenerator\Service;

use Tbessenreither\MultiLevelCache\CachedServiceGenerator\Attribute\MlcCachedService;
use Generator;
use RecursiveDirectoryIterator;
use RecursiveIteratorIterator;
use ReflectionClass;
use RuntimeException;
use SplFileInfo;

class FetchAllCachedServices
{
    /**
     * @return Generator<array{serviceName: string, reflection: ReflectionClass, cachedServiceAttr: MlcCachedService}>
     */
    public static function getAllAutogeneratedServices(?string $sourceDir = null): Generator
    {
        //fetch all classes that have the MlcCachedService Attribute
        $sourceDir = $sourceDir ?? self::getSrcDir();
        if (!is_dir($sourceDir)) {
            throw new RuntimeException("Source directory '$sourceDir' not found.");
        }

        $it = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($sourceDir));
        foreach ($it as $file) {
            /** @var SplFileInfo $file */
            if (!$file->isFile()) {
                continue;
            }

            // quick filter: only generated cached classes end with "Cached.php"
            if (!str_ends_with($file->getFilename(), '.php')) {
                continue;
            }

            $path = $file->getRealPath();
            if ($path === false) {
                continue;
            }

            $contents = file_get_contents($path);
            if ($contents === false) {
                continue;
            }

            // check for the attribute marker
            if (strpos($contents, '#[MlcCachedService') === false) {
                continue;
            }

            // extract namespace (if any)
            $namespace = '';
            if (preg_match('/^namespace\s+([^;]+);/m', $contents, $nsMatch)) {
                $namespace = trim($nsMatch[1]);
            }

            // extract the class name
            $fqcn = '';
            if (preg_match('/class\s+([A-Za-z_\x80-\xff][A-Za-z0-9_\x80-\xff]*)/m', $contents, $classMatch)) {
                $className = $classMatch[1];
                $fqcn = $namespace !== '' ? $namespace . '\\' . $className : $className;
            }

            if ($fqcn === '') {
                continue;
            }


            $reflection = new ReflectionClass($fqcn);
            $attributes = $reflection->getAttributes(MlcCachedService::class);

            if (empty($attributes)) {
                continue;
            }
            /** @var MlcCachedService $cachedServiceAttr */
            $cachedServiceAttr = $attributes[0]->newInstance();

            yield [
                'serviceName' => $fqcn,
                'reflection' => $reflection,
                'cachedServiceAttr' => $cachedServiceAttr,
            ];
        }
    }
    private static function getSrcDir(): string
    {
        $currentDir = dirname(__DIR__);

        // Traverse up until we find the "vendor" directory either as the current directory or in the parent directory as a sibling (When ran in Unit Tests).
        while (basename($currentDir) !== 'vendor' && !file_exists($currentDir.'/../vendor') && mb_strlen($currentDir) > 1) {
            $currentDir = dirname($currentDir);
        }

        // Now go up one more level to get to the root of the project
        $currentDir = dirname($currentDir);

        $sourceDir = $currentDir.'/src';

        if (!is_dir($sourceDir)) {
            throw new RuntimeException("Source directory '$sourceDir' not found.");
        }
        return $sourceDir;
    }
}
