<?php

declare(strict_types=1);

namespace Tbessenreither\MultiLevelCache\Tests\CachedServiceGenerator\Service;

use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\UsesClass;
use PHPUnit\Framework\TestCase;
use ReflectionMethod;
use RuntimeException;
use Tbessenreither\MultiLevelCache\CachedServiceGenerator\Attribute\MlcCachedService;
use Tbessenreither\MultiLevelCache\CachedServiceGenerator\Service\FetchAllCachedServices;

#[CoversClass(FetchAllCachedServices::class)]
#[UsesClass(MlcCachedService::class)]
class FetchAllCachedServicesTest extends TestCase
{
    public function testFetchServicesDefault(): void
    {
        $services = FetchAllCachedServices::getAllAutogeneratedServices();
        $this->assertIsIterable($services);
        foreach ($services as $service) {
            break;
        }
    }

    public function testFetchServicesEmpty(): void
    {
        $services = FetchAllCachedServices::getAllAutogeneratedServices(sourceDir: __DIR__ . '/TestSrcEmpty');
        $this->assertIsIterable($services);
        $count = 0;
        foreach ($services as $service) {
            $count++;
        }
        $this->assertSame(0, $count);
    }

    public function testFetchServicesExisting(): void
    {
        $services = FetchAllCachedServices::getAllAutogeneratedServices(sourceDir: __DIR__ . '/TestSrc');
        $this->assertIsIterable($services);
        $count = 0;
        foreach ($services as $service) {
            $count++;
        }
        $this->assertSame(1, $count);
    }

    public function testFetchServicesNonExistantDirectory(): void
    {
        $this->expectException(RuntimeException::class);
        $services = FetchAllCachedServices::getAllAutogeneratedServices(sourceDir: __DIR__ . '/TestSrcNonexistant');
        $this->assertIsIterable($services);
        foreach ($services as $service) {
            break;
        }
    }

    public function testGetSrcDirByVendorMaxIterationsExceeded(): void
    {
        $sourceDir = __DIR__ . '/FetchAllCachedServicesTestStructure/ExistingVendorWithSrc';
        $method = new ReflectionMethod(FetchAllCachedServices::class, 'getSrcDirByVendor');
        $src = $method->invoke(null, $sourceDir . '/1/2/3/4/5/6/7/8/9', 5);
        $this->assertFalse($src);
    }

    public function testGetSrcDirByVendorSibling(): void
    {
        $sourceDir = __DIR__ . '/FetchAllCachedServicesTestStructure/ExistingVendorWithSrc';
        $method = new ReflectionMethod(FetchAllCachedServices::class, 'getSrcDirByVendor');
        $src = $method->invoke(null, $sourceDir . '/1/2/3/4/5');

        $this->assertSame($sourceDir . '/src', $src);
    }

    public function testGetSrcDirByVendorSiblingWithoutSrc(): void
    {
        $sourceDir = __DIR__ . '/FetchAllCachedServicesTestStructure/ExistingVendorWithoutSrc';
        $method = new ReflectionMethod(FetchAllCachedServices::class, 'getSrcDirByVendor');
        $src = $method->invoke(null, $sourceDir . '/1/2/3/4/5');

        $this->assertFalse($src);
    }

    public function testGetSrcDirByVendorWithinSrc(): void
    {
        $sourceDir = __DIR__ . '/FetchAllCachedServicesTestStructure/ExistingVendorWithSrc';
        $method = new ReflectionMethod(FetchAllCachedServices::class, 'getSrcDirByVendor');
        $src = $method->invoke(null, $sourceDir . '/1/2/3/4/5');

        $this->assertSame($sourceDir . '/src', $src);
    }

    public function testGetSrcDirByComposerJsonMaxIterationsExceeded(): void
    {
        $sourceDir = __DIR__ . '/FetchAllCachedServicesTestStructure/ExistingComposerWithSrc';
        $method = new ReflectionMethod(FetchAllCachedServices::class, 'getSrcByComposerJson');
        $src = $method->invoke(null, $sourceDir . '/1/2/3/4/5/6/7/8/9', 5);
        $this->assertFalse($src);
    }

    public function testGetSrcDirByComposerJsonWithSrc(): void
    {
        $sourceDir = __DIR__ . '/FetchAllCachedServicesTestStructure/ExistingComposerWithSrc';
        $method = new ReflectionMethod(FetchAllCachedServices::class, 'getSrcByComposerJson');
        $src = $method->invoke(null, $sourceDir . '/1/2/3/4/5');

        $this->assertSame($sourceDir . '/src', $src);
    }

    public function testGetSrcDirByComposerJsonWithoutSrc(): void
    {
        $sourceDir = __DIR__ . '/FetchAllCachedServicesTestStructure/ExistingComposerWithoutSrc';
        $method = new ReflectionMethod(FetchAllCachedServices::class, 'getSrcByComposerJson');
        $src = $method->invoke(null, $sourceDir . '/1/2/3/4/5');

        $this->assertFalse($src);
    }

    public function testGetSrcDirSucceedingComposer(): void
    {
        $sourceDir = __DIR__ . '/FetchAllCachedServicesTestStructure/ExistingComposerWithSrc';
        $method = new ReflectionMethod(FetchAllCachedServices::class, 'getSrcDir');
        $src = $method->invoke(null, $sourceDir . '/1/2/3/4/5');

        $this->assertSame($sourceDir . '/src', $src);
    }

    public function testGetSrcDirSucceedingVendor(): void
    {
        $sourceDir = __DIR__ . '/FetchAllCachedServicesTestStructure/ExistingVendorWithSrc';
        $method = new ReflectionMethod(FetchAllCachedServices::class, 'getSrcDir');
        $src = $method->invoke(null, $sourceDir . '/1/2/3/4/5');

        $this->assertSame($sourceDir . '/src', $src);
    }

    public function testGetSrcDirFailing(): void
    {
        $this->expectException(RuntimeException::class);

        $sourceDir = __DIR__ . '/FetchAllCachedServicesTestStructure/ExistingVendorWithoutSrc';
        $method = new ReflectionMethod(FetchAllCachedServices::class, 'getSrcDir');
        $src = $method->invoke(null, $sourceDir . '/1/2/3/4/5');
    }
}
