<?php

declare(strict_types=1);

namespace Tbessenreither\MultiLevelCache\Tests\CachedServiceGenerator\Service;

use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\UsesClass;
use PHPUnit\Framework\TestCase;
use RuntimeException;
use Tbessenreither\MultiLevelCache\CachedServiceGenerator\Attribute\MlcCachedService;
use Tbessenreither\MultiLevelCache\CachedServiceGenerator\Service\FetchAllCachedServices;

#[CoversClass(FetchAllCachedServices::class)]
#[UsesClass(MlcCachedService::class)]
class FetchAllCachedServicesTest extends TestCase
{
    public function testFetchServicesDefault(): void
    {
        $services = FetchAllCachedServices::getAllAutogeneratedServices();
        $this->assertIsIterable($services);
        foreach ($services as $service) {
            break;
        }
    }

    public function testFetchServicesEmpty(): void
    {
        $services = FetchAllCachedServices::getAllAutogeneratedServices(sourceDir: __DIR__.'/TestSrcEmpty');
        $this->assertIsIterable($services);
        $count = 0;
        foreach ($services as $service) {
            $count++;
        }
        $this->assertSame(0, $count);
    }

    public function testFetchServicesExisting(): void
    {
        $services = FetchAllCachedServices::getAllAutogeneratedServices(sourceDir: __DIR__.'/TestSrc');
        $this->assertIsIterable($services);
        $count = 0;
        foreach ($services as $service) {
            $count++;
        }
        $this->assertSame(1, $count);
    }

    public function testFetchServicesNonExistantDirectory(): void
    {
        $this->expectException(RuntimeException::class);
        $services = FetchAllCachedServices::getAllAutogeneratedServices(sourceDir: __DIR__.'/TestSrcNonexistant');
        $this->assertIsIterable($services);
        foreach ($services as $service) {
            break;
        }
    }
}
