name: PHP Unit Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: php:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y git unzip curl

      - name: Install Redis PHP extension
        run: |
          pecl install redis pcov
          docker-php-ext-enable redis pcov

      - name: Install Composer
        run: |
          curl -sS https://getcomposer.org/installer -o composer-setup.php
          php composer-setup.php --install-dir=/usr/local/bin --filename=composer
          composer --version

      - name: Install composer dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Run tests
        run: composer run-script test
